/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class frmAgregarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmAgregarUsuario
     */
    public frmAgregarUsuario() {
        initComponents();
        this.setTitle("Registro de Usuarios");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtUnombre = new javax.swing.JTextField();
        txtUapellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUnick = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUpass = new javax.swing.JPasswordField();
        btnUaceptar = new javax.swing.JButton();
        btnUcancelar = new javax.swing.JButton();
        btnUsalir = new javax.swing.JButton();
        comboxtipo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 20));

        txtUnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnombreActionPerformed(evt);
            }
        });
        txtUnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtUnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 100, -1));

        txtUapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUapellidoActionPerformed(evt);
            }
        });
        txtUapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUapellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtUapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 20));

        txtUnick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnickActionPerformed(evt);
            }
        });
        getContentPane().add(txtUnick, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nick:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 30, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Contraseña:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        txtUpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 100, -1));

        btnUaceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUaceptar.setText("Aceptar");
        btnUaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUaceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnUaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        btnUcancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUcancelar.setText("Cancelar");
        btnUcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnUcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        btnUsalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUsalir.setText("Volver");
        btnUsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 70, 20));

        comboxtipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboxtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        comboxtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxtipoActionPerformed(evt);
            }
        });
        getContentPane().add(comboxtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Contraseña:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tipo de Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondoAgregarUsuario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 324));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnombreActionPerformed
          if ("".equals(txtUnombre.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtUnombre.requestFocus();
        } else {
            txtUapellido.requestFocus();
        }
    }//GEN-LAST:event_txtUnombreActionPerformed

    private void txtUapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUapellidoActionPerformed
          if ("".equals(txtUapellido.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtUapellido.requestFocus();
        } else {
            txtUnick.requestFocus();
        }
    }//GEN-LAST:event_txtUapellidoActionPerformed

    private void txtUnickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnickActionPerformed
          if ("".equals(txtUnick.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtUnick.requestFocus();
        } else {
            txtUpass.requestFocus();
        }
    }//GEN-LAST:event_txtUnickActionPerformed

    private void txtUpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpassActionPerformed
          if ("".equals(txtUpass.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtUpass.requestFocus();
        } else {
            btnUaceptar.requestFocus();
        }
    }//GEN-LAST:event_txtUpassActionPerformed

    private void txtUnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnombreKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtUnombreKeyTyped

    private void txtUapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUapellidoKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtUapellidoKeyTyped

    private void btnUcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcancelarActionPerformed
        this.dispose();
       Sistema frmS = new Sistema();
                frmS.setVisible(true);
    }//GEN-LAST:event_btnUcancelarActionPerformed

    private void btnUaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUaceptarActionPerformed
          this.dispose();
        frmUsuario frm = new frmUsuario();
                frm.setVisible(true);
               
    }//GEN-LAST:event_btnUaceptarActionPerformed

    private void btnUsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsalirActionPerformed
         this.dispose();
        Sistema frmS = new Sistema();
                frmS.setVisible(true);
                
    }//GEN-LAST:event_btnUsalirActionPerformed

    private void comboxtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxtipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgregarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnUaceptar;
    public javax.swing.JButton btnUcancelar;
    public javax.swing.JButton btnUsalir;
    public javax.swing.JComboBox<String> comboxtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField txtUapellido;
    public javax.swing.JTextField txtUnick;
    public javax.swing.JTextField txtUnombre;
    public javax.swing.JPasswordField txtUpass;
    // End of variables declaration//GEN-END:variables

    int getTipo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
