/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import consulta.consultaAgregar;
import controlador.ctlAgregar;
import modelo.modeloAgregar;

/**
 *
 * @author Fernando
 */
public class frmCiudad extends javax.swing.JFrame {

    /**
     * Creates new form frmCiudad
     */
    public frmCiudad() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtCiudad.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        btnCregistrar = new javax.swing.JButton();
        btnCeliminar = new javax.swing.JButton();
        btnCbuscar = new javax.swing.JButton();
        btnCvolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ciudad:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        getContentPane().add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 187, -1));

        btnCregistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCregistrar.setText("Registrar");
        btnCregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        btnCeliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCeliminar.setText("Eliminar");
        btnCeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        btnCbuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCbuscar.setText("Buscar");
        getContentPane().add(btnCbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        btnCvolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCvolver.setText("Volver");
        btnCvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCvolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnCvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/agregarEmpleado1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCvolverActionPerformed
         modeloAgregar modA = new modeloAgregar();
        consultaAgregar Cagg= new consultaAgregar();
        frmAgregar frm = new frmAgregar();
        ctlAgregar ctl = new ctlAgregar(modA, Cagg, frm);
        ctl.iniciar();
        frm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCvolverActionPerformed

    private void btnCregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCregistrarActionPerformed
        txtCiudad.requestFocus();
    }//GEN-LAST:event_btnCregistrarActionPerformed

    private void btnCeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeliminarActionPerformed
        txtCiudad.requestFocus();
    }//GEN-LAST:event_btnCeliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCiudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCbuscar;
    public javax.swing.JButton btnCeliminar;
    public javax.swing.JButton btnCregistrar;
    public javax.swing.JButton btnCvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField txtCiudad;
    // End of variables declaration//GEN-END:variables
}
