/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import consulta.consultaAgregar;
import controlador.ctlAgregar;
import modelo.modeloAgregar;

/**
 *
 * @author Fernando
 */
public class frmDepto2 extends javax.swing.JFrame {

    /**
     * Creates new form frmDepto
     */
    public frmDepto2() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtDepto.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDepto = new javax.swing.JTextField();
        btnDregistrar = new javax.swing.JButton();
        btnDeliminar = new javax.swing.JButton();
        btnDbuscar = new javax.swing.JButton();
        btnDvolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Departamento:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeptoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 179, -1));

        btnDregistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDregistrar.setText("Registrar");
        btnDregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btnDeliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDeliminar.setText("Eliminar");
        btnDeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        btnDbuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDbuscar.setText("Buscar");
        getContentPane().add(btnDbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        btnDvolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDvolver.setText("Volver");
        btnDvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDvolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnDvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/agregarEmpleado1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeptoActionPerformed
        btnDregistrar.requestFocus();
    }//GEN-LAST:event_txtDeptoActionPerformed

    private void btnDvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDvolverActionPerformed
         modeloAgregar modA = new modeloAgregar();
        consultaAgregar Cagg= new consultaAgregar();
        frmAgregar frm = new frmAgregar();
        ctlAgregar ctl = new ctlAgregar(modA, Cagg, frm);
        ctl.iniciar();
        frm.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnDvolverActionPerformed

    private void btnDregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDregistrarActionPerformed
        txtDepto.requestFocus();
    }//GEN-LAST:event_btnDregistrarActionPerformed

    private void btnDeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliminarActionPerformed
        txtDepto.requestFocus();
    }//GEN-LAST:event_btnDeliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDepto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDepto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDepto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDepto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDepto2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDbuscar;
    public javax.swing.JButton btnDeliminar;
    public javax.swing.JButton btnDregistrar;
    public javax.swing.JButton btnDvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField txtDepto;
    // End of variables declaration//GEN-END:variables
}
