/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class frmEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form frmEmpleados
     */
    public frmEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEcorreo = new javax.swing.JTextField();
        txtEcedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEedad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEdireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEtelefono = new javax.swing.JTextField();
        txtEid = new javax.swing.JTextField();
        btnEregistrar = new javax.swing.JButton();
        btnEmodificar = new javax.swing.JButton();
        btnEbuscar = new javax.swing.JButton();
        btnEeliminar = new javax.swing.JButton();
        btnElista = new javax.swing.JButton();
        btnJvolver = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cédula:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        txtEcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 170, -1));

        txtEcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcedulaActionPerformed(evt);
            }
        });
        txtEcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEcedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtEcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        txtEnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnombreActionPerformed(evt);
            }
        });
        txtEnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtEnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Apellido:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        txtEapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEapellidoActionPerformed(evt);
            }
        });
        txtEapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEapellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtEapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Edad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        txtEedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEedadActionPerformed(evt);
            }
        });
        txtEedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEedadKeyTyped(evt);
            }
        });
        getContentPane().add(txtEedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 50, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Dirección:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        txtEdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdireccionActionPerformed(evt);
            }
        });
        txtEdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdireccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtEdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Teléfono:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        txtEtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEtelefonoActionPerformed(evt);
            }
        });
        txtEtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEtelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtEtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, -1));

        txtEid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEidActionPerformed(evt);
            }
        });
        getContentPane().add(txtEid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 50, -1));

        btnEregistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEregistrar.setText("Registrar");
        getContentPane().add(btnEregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        btnEmodificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEmodificar.setText("Modificar");
        getContentPane().add(btnEmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        btnEbuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEbuscar.setText("Buscar");
        getContentPane().add(btnEbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        btnEeliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEeliminar.setText("Eliminar");
        getContentPane().add(btnEeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        btnElista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnElista.setText("Lista de Empleados");
        btnElista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElistaActionPerformed(evt);
            }
        });
        getContentPane().add(btnElista, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 130, -1, -1));

        btnJvolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnJvolver.setText("Volver");
        btnJvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJvolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnJvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/agregarEmpleado1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -80, 510, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEidActionPerformed

    private void btnElistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElistaActionPerformed
        frmListarEmpleados frmLE = new frmListarEmpleados();
        frmLE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnElistaActionPerformed

    private void btnJvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJvolverActionPerformed
        Sistema frm = new Sistema();
        frm.setVisible(true);
    }//GEN-LAST:event_btnJvolverActionPerformed

    private void txtEcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcedulaActionPerformed
          if ("".equals(txtEcedula.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtEcedula.requestFocus();
        } else {
            txtEnombre.requestFocus();
        }
    }//GEN-LAST:event_txtEcedulaActionPerformed

    private void txtEnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnombreActionPerformed
         if ("".equals(txtEnombre.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtEnombre.requestFocus();
        } else {
            txtEapellido.requestFocus();
        }
    }//GEN-LAST:event_txtEnombreActionPerformed

    private void txtEapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEapellidoActionPerformed
         if ("".equals(txtEapellido.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtEapellido.requestFocus();
        } else {
            txtEedad.requestFocus();
        }
    }//GEN-LAST:event_txtEapellidoActionPerformed

    private void txtEedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEedadActionPerformed
         if ("".equals(txtEedad.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtEedad.requestFocus();
        } else {
            txtEdireccion.requestFocus();
        }
    }//GEN-LAST:event_txtEedadActionPerformed

    private void txtEdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdireccionActionPerformed
         if ("".equals(txtEdireccion.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtEdireccion.requestFocus();
        } else {
            txtEtelefono.requestFocus();
        }
    }//GEN-LAST:event_txtEdireccionActionPerformed

    private void txtEtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEtelefonoActionPerformed
         if ("".equals(txtEtelefono.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtEtelefono.requestFocus();
        } else {
            txtEcorreo.requestFocus();
        }
    }//GEN-LAST:event_txtEtelefonoActionPerformed

    private void txtEcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcorreoActionPerformed
        if ("".equals(txtEcorreo.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtEcorreo.requestFocus();
        } else {
            btnEregistrar.requestFocus();
        }
    }//GEN-LAST:event_txtEcorreoActionPerformed

    private void txtEcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEcedulaKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_txtEcedulaKeyTyped

    private void txtEnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnombreKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtEnombreKeyTyped

    private void txtEapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEapellidoKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtEapellidoKeyTyped

    private void txtEedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEedadKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_txtEedadKeyTyped

    private void txtEdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdireccionKeyTyped

    }//GEN-LAST:event_txtEdireccionKeyTyped

    private void txtEtelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEtelefonoKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_txtEtelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEbuscar;
    public javax.swing.JButton btnEeliminar;
    public javax.swing.JButton btnElista;
    public javax.swing.JButton btnEmodificar;
    public javax.swing.JButton btnEregistrar;
    public javax.swing.JToggleButton btnJvolver;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField txtEapellido;
    public javax.swing.JTextField txtEcedula;
    public javax.swing.JTextField txtEcorreo;
    public javax.swing.JTextField txtEdireccion;
    public javax.swing.JTextField txtEedad;
    public javax.swing.JTextField txtEid;
    public javax.swing.JTextField txtEnombre;
    public javax.swing.JTextField txtEtelefono;
    // End of variables declaration//GEN-END:variables
}
