/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import bd.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class frmSalario extends javax.swing.JFrame {

    conexion c= new conexion();
    Connection con = c.getConexion();
    public frmSalario() {
        initComponents();
//        mostraEmpleado();
        
    }
    
    
//    public void mostraEmpleado() {
//        String sql = "SELECT * FROM empleados";
//        try {
//            Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//            while(rs.next()) {
//                
//                cboSalario.addItem(rs.getString("nomEm"));
//            }
//            
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(frmSalario.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboEm = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtScargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSguardar = new javax.swing.JButton();
        btnScancelar = new javax.swing.JButton();
        txtSsalario = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboEm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEmActionPerformed(evt);
            }
        });
        getContentPane().add(cboEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Empleado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cargo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        txtScargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScargoActionPerformed(evt);
            }
        });
        txtScargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtScargoKeyTyped(evt);
            }
        });
        getContentPane().add(txtScargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Salario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 20));

        btnSguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSguardar.setText("Guardar");
        btnSguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btnScancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnScancelar.setText("Cancelar");
        getContentPane().add(btnScancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        txtSsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsalarioActionPerformed(evt);
            }
        });
        txtSsalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSsalarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtSsalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, -1));

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Salario1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -80, 730, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSguardarActionPerformed
        
        
    }//GEN-LAST:event_btnSguardarActionPerformed

    private void cboEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEmActionPerformed
        txtScargo.requestFocus();
    }//GEN-LAST:event_cboEmActionPerformed

    private void txtScargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScargoActionPerformed
        if ("".equals(txtScargo.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtScargo.requestFocus();
        } else {
            txtSsalario.requestFocus();
        }
    }//GEN-LAST:event_txtScargoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Sistema frm = new Sistema();
        frm.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtSsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsalarioActionPerformed
        if ("".equals(txtSsalario.getText())) {

            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            txtSsalario.requestFocus();
        } else {
            btnSguardar.requestFocus();
        }
    }//GEN-LAST:event_txtSsalarioActionPerformed

    private void txtScargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtScargoKeyTyped
         char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtScargoKeyTyped

    private void txtSsalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSsalarioKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_txtSsalarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSalario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnScancelar;
    public javax.swing.JButton btnSguardar;
    public javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> cboEm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField txtScargo;
    public javax.swing.JTextField txtSsalario;
    // End of variables declaration//GEN-END:variables

    
}
