/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import bd.conexion;
import consulta.ConsultaAggUsuario;
import consulta.consultaAgregar;
import consulta.consultaEmpleado;
import consulta.consultaSalario;
import controlador.ctlAgregar;
import controlador.ctlAgregarUsuario;
import controlador.ctlEmpleado;
import controlador.ctlSalario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import modelo.modeloAggUsuario;
import modelo.modeloAgregar;
import modelo.modeloEmpleado;
import modelo.modeloSalario;

/**
 *
 * @author Fernando
 */
public class Sistema extends javax.swing.JFrame {

    conexion c= new conexion();
    Connection con = c.getConexion();
    
    

    @Override
    public void setTitle(String string) {
        super.setTitle(string); //To change body of generated methods, choose Tools | Templates.
    }
    public Sistema() {
        initComponents();
        this.setTitle("Censo 2022");
        this.setLocationRelativeTo(null);
        
    }
        
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAgregar = new javax.swing.JMenuItem();
        jMenuBuscar = new javax.swing.JMenuItem();
        jMenuEstadistica = new javax.swing.JMenu();
        jMenuEmpleados = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuPagodeSalario = new javax.swing.JMenu();
        jMenuSalario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuAggU = new javax.swing.JMenuItem();
        jMenuCambiarU = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdmin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblAdmin.setText("Administrador");
        getContentPane().add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo_Sistema.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 400));

        jMenu1.setText("Encuestas");

        jMenuAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAgregar.setText("Agregar Encuesta");
        jMenuAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAgregar);

        jMenuBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuBuscar.setText("Buscar Encuesta");
        jMenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuBuscar);

        jMenuBar1.add(jMenu1);

        jMenuEstadistica.setText("Estadísticas");
        jMenuBar1.add(jMenuEstadistica);

        jMenuEmpleados.setText("Empleados");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Agregar Empleados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItem1);

        jMenuBar1.add(jMenuEmpleados);

        jMenuPagodeSalario.setText("Pago de Salario");

        jMenuSalario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSalario.setText("Salario");
        jMenuSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalarioActionPerformed(evt);
            }
        });
        jMenuPagodeSalario.add(jMenuSalario);

        jMenuBar1.add(jMenuPagodeSalario);

        jMenu3.setText("Configuración");

        jMenuAggU.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAggU.setText("Crear Usuario");
        jMenuAggU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAggUActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuAggU);

        jMenuCambiarU.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCambiarU.setText("Cambiar Usuario");
        jMenuCambiarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCambiarUActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCambiarU);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgregarActionPerformed
        modeloAgregar modA = new modeloAgregar();
        consultaAgregar Cagg= new consultaAgregar();
        frmAgregar frm = new frmAgregar();
        ctlAgregar ctl = new ctlAgregar(modA, Cagg, frm);
        ctl.iniciar();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuAgregarActionPerformed

    private void jMenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarActionPerformed
        this.dispose();
        frmBuscarEncuesta cu = new frmBuscarEncuesta();
        cu.setLocationRelativeTo(null);
        cu.setVisible(true); 
    }//GEN-LAST:event_jMenuBuscarActionPerformed

    private void jMenuAggUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAggUActionPerformed
        this.dispose();
        modeloAggUsuario modAgg = new modeloAggUsuario();
        ConsultaAggUsuario cAgg = new ConsultaAggUsuario();
        frmAgregarUsuario frmAgg = new frmAgregarUsuario();
        ctlAgregarUsuario ctlA = new ctlAgregarUsuario(modAgg, cAgg, frmAgg);
        ctlA.iniciar();
        frmAgg.setLocationRelativeTo(null);
        frmAgg.setVisible(true);
    }//GEN-LAST:event_jMenuAggUActionPerformed

    private void jMenuCambiarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCambiarUActionPerformed
        this.dispose();
        frmUsuario frm = new frmUsuario();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuCambiarUActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        modeloEmpleado modEm = new modeloEmpleado();
        consultaEmpleado cEm = new consultaEmpleado();
        frmEmpleado frmEm = new frmEmpleado();
        ctlEmpleado ctlEm = new ctlEmpleado(modEm, cEm, frmEm);
        ctlEm.iniciar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalarioActionPerformed
        this.dispose();
        modeloSalario modSa = new modeloSalario();
        consultaSalario conSa = new consultaSalario();
        frmSalario frmSa = new frmSalario();
        ctlSalario ctlSa = new ctlSalario(modSa, conSa, frmSa);
        ctlSa.iniciar();
        
    }//GEN-LAST:event_jMenuSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    public javax.swing.JMenuItem jMenuAggU;
    private javax.swing.JMenuItem jMenuAgregar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBuscar;
    public javax.swing.JMenuItem jMenuCambiarU;
    private javax.swing.JMenu jMenuEmpleados;
    public javax.swing.JMenu jMenuEstadistica;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuPagodeSalario;
    private javax.swing.JMenuItem jMenuSalario;
    public javax.swing.JLabel lblAdmin;
    // End of variables declaration//GEN-END:variables

    private void cargar_Tabla() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
